development:
  adapter: postgresql
  encoding: unicode
  database: banzai_barn_development
  pool: 5
  username: dbuser

test:
  adapter: postgresql
  encoding: unicode
  database: banzai_barn_test
  pool: 5
  username: dbuser

production:
  adapter: postgresql
  encoding: unicode
  database: banzai_barn_production
  pool: 5
  username: dbuser
